swagger: '2.0'
info:
  title: Loaner
  description: Loaner web service API
  version: "1.0.0.0"
basePath: /
produces:
  - application/json
paths:
  /clients:
    get:
      summary: Get list of clients
      responses:
        200:
          description: List of clients
          schema:
            type: array
            items:
              $ref: '#/definitions/ClientDTO'
  /clients/{id}:
    get:
      summary: Get Client by given ID
      parameters:
          - name: id
            in: path
            required: true
            type: number
            description: id of a client to retrieve
      responses:
        200:
          description: Client information
          schema:
            $ref: '#/definitions/ClientDTO'
  /clients/{id}/loans:
    get:
      summary: Get client's approve loan list
      parameters:
        - name: id
          in: path
          required: true
          type: number
          description: id of a client to get loans from
      responses:
        200:
          description: List of approved loans
          schema:
            type: array
            items:
              $ref: '#/definitions/LoanDTO'
  /loans:
    get:
      summary: Get list of all approved loans
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/LoanDTO'
    post:
      summary: Create a new loan
      responses:
        201:
          description: Loan succesfuly created
  /loans/{id}:
    get:
      summary: Get loan by given id
      parameters:
      - name: id
        description: is of a loan to retrieve
        in: path
        required: true
        type: number
      responses:
        200:
          description: Requested loan
          schema:
            $ref: '#/definitions/LoanDTO'
definitions:
  ClientDTO:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Uniq id of a client
      name:
        type: string
        description: Client's name. (max 200)
      surname:
        type: string
        description: Client's surname. (max 200)
      personalId:
        type: string
        description: Client's personal id. (max 200)
  LoanDTO:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Loan uniq id.
      amount:
        type: number
        format: double
        description: amount of maney
      client:
        $ref: '#/definitions/ClientDTO'
      term:
        type: string
        format: date
        description: Return term for loan.